name: PHP Composer

on: [push, pull_request]

jobs:
  build:

    runs-on: ${{ matrix.runner }}

    strategy:
        fail-fast: true
        matrix:
            php: ['5.3', '5.4', '5.5', '5.6', '7.0', '7.1', '7.2', '7.3', '7.4', '8.0', '8.1']
            runner: ['ubuntu-18.04', 'ubuntu-20.04']

    name: PHP ${{ matrix.php }} on ${{ matrix.runner }}
    steps:
    - uses: actions/checkout@v3
    
    - name: Install PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php }}
        
    - name: Report PHP version
      run: php -v

    - name: Validate composer.json and composer.lock
      run: composer validate --strict

    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v3
      with:
        path: vendor
        key: ${{ matrix.runner }}-php${{ matrix.php }}-${{ hashFiles('**/composer.lock') }}
        restore-keys: ${{ matrix.runner }}-php${{ matrix.php }}-

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress --no-suggest

    - name: Run test suite
      run: composer test
      if: ${{ matrix.php != '5.3' && matrix.php != '5.4' && matrix.php != '5.5' }}
      
    - name: Run test suite
      run: vendor/bin/phpunit --verbose
      if: ${{ matrix.php == '5.3' || matrix.php == '5.4' || matrix.php == '5.5' }}
